### ISSUE TITLE
Request to Add Support for MySQL Versions Prior to 5.7 (e.g., 5.0 and 5.6) in Zig Library

### ISSUE THREAD

**Issue by gaogaogoo** [speed2exe/myzql#12]
I hope this message finds you well. I am currently using your Zig library and would like to request support for MySQL versions prior to 5.7, specifically versions like 5.0 and 5.6. It appears that the library is primarily optimized for newer MySQL versions, and I have a requirement to interact with databases running on older MySQL installations.

Could you please consider adding compatibility for MySQL versions such as 5.0 and 5.6 in your library? Alternatively, any guidance on how to adapt the library to work with these older versions would be greatly appreciated.

Thank you for your attention to this matter. I look forward to your response.

**Comment by speed2exe** [comment]
@gaogaogoo Thanks for filing this issue. Yes, you are right that this lib is mostly for newer version of MySQL, as I would have assume that most users wont have MySQL version older than that. Are 5.0 and 5.6 the versions of MySQL which you are using this library to connect to?

**Comment by gaogaogoo** [comment]
> @gaogaogoo Thanks for filing this issue. Yes, you are right that this lib is mostly for newer version of MySQL, as I would have assume that most users wont have MySQL version older than that. Are 5.0 and 5.6 the versions of MySQL which you are using this library to connect to?

Yes, I am trying to use the library to connect to MySQL version 5.0, but it returns an UnsupportedAuthPlugin error. We have some old projects without source code that cannot be updated but require further functionality, so we need to connect to older MySQL versions. We like the Zig language and plan to use it in future work, so we hope to use this library.

**Comment by speed2exe** [comment]
@gaogaogoo What is the name of the plugin? It should be printed along with the error

https://github.com/speed2exe/myzql/blob/main/src/conn.zig#L86

**Comment by gaogaogoo** [comment]
I re-tested it and encountered the array out-of-bounds error again. After considering it, I plan to use Zig to statically link the Rust MySQL client library and access MySQL through Rust to resolve the issue of MySQL not supporting older versions. Thank you, and I'll close this issue for now.
