### ISSUE TITLE
Failed to build the tag myzql-0.13.0 by zig-0.13.0

### ISSUE THREAD

**Issue by forchid** [speed2exe/myzql#13]
Can't build the [myzql-0.13.0](https://github.com/speed2exe/myzql/releases/tag/0.13.0) by zig-0.13.0, but ok by zig-0.12.0.

**Comment by speed2exe** [comment]
@forchid are you using the main branch? you might want to use tag `0.13.0`

**Comment by forchid** [comment]
@speed2exe Thanks. Building the tag [myzql-0.13.1](https://github.com/speed2exe/myzql/releases/tag/0.13.1) ok by zig-0.13.0.
